apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-webhook-cluster-access
  labels:
    app.kubernetes.io/component: webhook
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
      - customresourcedefinitions/status
    verbs:
      - get
      - list
      - update
      - patch
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resourceNames:
      - webhook.pipeline.tekton.dev
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - update
      - delete
  - apiGroups:
      - admissionregistration.k8s.io
    resourceNames:
      - validation.webhook.pipeline.tekton.dev
      - config.webhook.pipeline.tekton.dev
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - update
      - delete
  - apiGroups:
      - policy
    resourceNames:
      - tekton-pipelines
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups:
      - ""
    resourceNames:
      - tekton-pipelines
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - tekton-pipelines
    resources:
      - namespaces/finalizers
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-webhook-cluster-access
  labels:
    app.kubernetes.io/component: webhook
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "tekton-pipelines.fullname" . }}-webhook-cluster-access'
subjects:
  - kind: ServiceAccount
    name: '{{ include "tekton-pipelines.fullname" . }}-webhook'
    namespace: '{{ .Release.Namespace }}'