apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
  {{- include "tekton-pipelines.labels" . | nindent 4 }}