apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  labels:
    app.kubernetes.io/name: autoscaler
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: 1.0.1
    serving.knative.dev/release: v1.0.1
  {{- include "knative-serving.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 604cb513
data:
  _example: {{ .Values.configAutoscaler.Example | quote }}