apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  labels:
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: 1.0.1
    serving.knative.dev/release: v1.0.1
  {{- include "knative-serving.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: cdabec96
data:
  _example: {{ .Values.configDefaults.Example | quote }}