apiVersion: core.openfunction.io/v1alpha2
kind: Domain
metadata:
  name: openfunction
  namespace: io
  labels:
  {{- include "openfunction.labels" . | nindent 4 }}
spec:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace
    ingressClassName: nginx
    service:
      name: ingress-nginx-controller
      namespace: ingress-nginx