---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: io

---
apiVersion: core.openfunction.io/v1alpha2
kind: Domain
metadata:
  name: openfunction
  namespace: io
spec:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    service:
      name: ingress-nginx-controller
      namespace: ingress-nginx
    ingressClassName: nginx
