# permissions for end users to view eventbus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventbus-viewer-role
rules:
- apiGroups:
  - events.openfunction.io
  resources:
  - eventbus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.openfunction.io
  resources:
  - eventbus/status
  verbs:
  - get
