# permissions for end users to edit eventbus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventbus-editor-role
rules:
- apiGroups:
  - events.openfunction.io
  resources:
  - eventbus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.openfunction.io
  resources:
  - eventbus/status
  verbs:
  - get
