apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller-cluster-access
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - clustertasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
      - runs
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns/finalizers
      - pipelineruns/finalizers
      - runs/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - tasks/status
      - clustertasks/status
      - taskruns/status
      - pipelines/status
      - pipelineruns/status
      - pipelineresources/status
      - runs/status
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller-tenant-access
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - limitranges
      - secrets
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller-cluster-access
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "tekton-pipelines.fullname" . }}-controller-cluster-access'
subjects:
  - kind: ServiceAccount
    name: '{{ include "tekton-pipelines.fullname" . }}-controller'
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller-tenant-access
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "tekton-pipelines.fullname" . }}-controller-tenant-access'
subjects:
  - kind: ServiceAccount
    name: '{{ include "tekton-pipelines.fullname" . }}-controller'
    namespace: '{{ .Release.Namespace }}'