apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - config-logging
      - config-observability
      - config-artifact-bucket
      - config-artifact-pvc
      - feature-flags
      - config-leader-election
      - config-registry-cert
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - policy
    resourceNames:
      - tekton-pipelines
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "tekton-pipelines.fullname" . }}-controller'
subjects:
  - kind: ServiceAccount
    name: '{{ include "tekton-pipelines.fullname" . }}-controller'
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller-leaderelection
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "tekton-pipelines.fullname" . }}-leader-election'
subjects:
  - kind: ServiceAccount
    name: '{{ include "tekton-pipelines.fullname" . }}-controller'
    namespace: '{{ .Release.Namespace }}'