apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.labels" . | nindent 4 }}