apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller
  labels:
    app: tekton-pipelines-controller
    app.kubernetes.io/component: controller
    pipeline.tekton.dev/release: {{ .Values.pipelinesInfo.version }}
    version: {{ .Values.pipelinesInfo.version }}
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.type }}
  selector:
    app.kubernetes.io/component: controller
  {{- include "tekton-pipelines.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.controller.ports | toYaml | nindent 2 -}}