apiVersion: v1
kind: Service
metadata:
  name: activator-service
  labels:
    app: activator
    app.kubernetes.io/name: activator
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: 1.0.1
    serving.knative.dev/release: v1.0.1
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.activatorService.type }}
  selector:
    app: activator
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.activatorService.ports | toYaml | nindent 2 -}}