apiVersion: v1
kind: Service
metadata:
  name: autoscaler
  labels:
    app: autoscaler
    app.kubernetes.io/name: autoscaler
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: 1.0.1
    serving.knative.dev/release: v1.0.1
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.autoscaler.type }}
  selector:
    app: autoscaler
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.autoscaler.ports | toYaml | nindent 2 -}}