- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/redis/additionalProperties/properties/metadata/items/properties/value/type
  value: ""
- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/kafka/additionalProperties/properties/metadata/items/properties/value/type
  value: ""