- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/serving/properties/openFuncAsync/properties/dapr/properties/components/items/properties/metadata/items/properties/value/type
  value: ""
- op: replace
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/serving/properties/openFuncAsync/properties/dapr/properties/components/additionalProperties/properties/metadata/items/properties/value/type
  value: ""