apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
spec:
  version: "v1.0.0"
  image: "openfunctiondev/v1beta1-sample:latest"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 3
    timeout: 10m
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/knative/hello-world-go"
  serving:
    timeout: 5m
    runtime: knative
    template:
      containers:
        - name: function
          imagePullPolicy: Always
