apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "openfunction.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "openfunction.fullname" . }}-serving-cert
  labels:
  {{- include "openfunction.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "openfunction.fullname" . }}-webhook-service'
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-openfunction-io-v1beta1-function
  failurePolicy: Fail
  name: mfunctions.of.io
  rules:
  - apiGroups:
    - core.openfunction.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "openfunction.fullname" . }}-webhook-service'
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-openfunction-io-v1beta1-serving
  failurePolicy: Fail
  name: mservings.of.io
  rules:
  - apiGroups:
    - core.openfunction.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servings
  sideEffects: None