apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: 1.0.1
    role: webhook
    serving.knative.dev/release: v1.0.1
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.type }}
  selector:
    role: webhook
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.webhook.ports | toYaml | nindent 2 -}}