apiVersion: v1
kind: Service
metadata:
  name: kourier
  namespace: kourier-system
  labels:
    networking.knative.dev/ingress-provider: kourier
    serving.knative.dev/release: v1.0.1
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kourier.type }}
  selector:
    app: 3scale-kourier-gateway
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.kourier.ports | toYaml | nindent 2 -}}