apiVersion: v1
kind: Namespace
metadata:
  name: kourier-system
  labels:
    networking.knative.dev/ingress-provider: kourier
    serving.knative.dev/release: "v1.0.1"
  {{- include "knative-serving.labels" . | nindent 4 }}