name: Main CI WorkFlow

on:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'
    paths:
      - '.github/workflows/**'
      - 'apis/**'
      - 'config/bundle.yaml'
      - 'controllers/**'
      - 'hack/delete.sh'
      - 'hack/deploy.sh'
      - 'pkg/**'
      - 'Dockerfile'
      - 'main.go'
      - 'Makefile'
  pull_request:
    branches:
      - 'main'
      - 'release-*'
    paths:
      - '.github/workflows/**'
      - 'apis/**'
      - 'config/bundle.yaml'
      - 'controllers/**'
      - 'hack/delete.sh'
      - 'hack/deploy.sh'
      - 'pkg/**'
      - 'Dockerfile'
      - 'main.go'
      - 'Makefile'
env:
  TAG: action-${{ github.run_number }}
  REGISTRY_SERVER: https://index.docker.io/v1/
  REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Verify and Unit Test
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install kubebuilder-3.1.0
        run: |
          curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_linux_amd64"
          chmod +x kubebuilder && mv kubebuilder /usr/local/bin/
      - name: Run basic test
        run: make test

      - name: Run verify crds test
        run:  make verify

  docker_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and Push image
        run: |
          docker build . -t openfunctiondev/openfunction:${{ env.TAG }} -f Dockerfile --build-arg GOPROXY="https://proxy.golang.org"
          docker push openfunctiondev/openfunction:${{ env.TAG }}

  e2e_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: E2E Tests
    needs: docker_build
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: .github/workflows/kind/kind.yaml

      - name: Install OpenFunction
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/install.sh"
          bash "${GITHUB_WORKSPACE}"/.github/workflows/install.sh ${{ env.TAG }}

      - name: Create push-secret
        run: |
          kubectl create secret docker-registry push-secret \
              --docker-server=${{ env.REGISTRY_SERVER }} \
              --docker-username=${{ env.REGISTRY_USER }} \
              --docker-password=${{ env.REGISTRY_PASSWORD }} 

      - name: Test
        run: |
          export TAG=${{ env.TAG }}
          export TEST_NAMESPACE=default
          make e2e-test

      - name: Output debug info
        if: ${{ failure() }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/output.sh"
          bash "${GITHUB_WORKSPACE}"/.github/workflows/output.sh
